# Generated by Django 4.1 on 2022-09-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_cart_id_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="prodcut",
            new_name="product",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
